//! Emission: resolved models → formatted `.rs` file contents.
//!
//! TokenStreams are built with `quote`, parsed into a `syn::File` and
//! formatted with `prettyplease` — one formatter, bundled, so the same
//! schema and config produce byte-identical output on every machine
//! (rustfmt versions never enter the picture). Identifiers are
//! path-qualified throughout instead of managing `use` lists: Rust needs no
//! import management, and a generated file with zero imports can never trip
//! an unused-import lint. The two `as _` trait imports a preload body needs
//! are function-local and always used.

mod model;

use proc_macro2::TokenStream;
use quote::quote;

use crate::config::{Config, Dialect};
use crate::error::{GenError, Result};
use crate::resolve::Model;

/// The fixed first lines of every generated file. `@generated` is the marker
/// review tools key on; no timestamps, no versions — determinism includes
/// the header.
const HEADER: &str = "// @generated by keelson-gen. DO NOT EDIT.\n\
                      // Regenerate from the schema instead; hand-written code (hooks included)\n\
                      // belongs outside this directory.\n";

/// What the dialect contributes to emission: the crate its statements come
/// from. The model machinery is dialect-generic; this is the whole
/// difference between a psql and a sqlite model file.
pub(crate) struct Dial {
    pub(crate) krate: TokenStream,
}

impl Dial {
    pub(crate) fn new(dialect: Dialect) -> Result<Dial> {
        let krate = match dialect {
            Dialect::Psql => quote!(keelson_psql),
            Dialect::Sqlite => quote!(keelson_sqlite),
            Dialect::Mysql => {
                return Err(GenError::Unsupported(
                    "MySQL emission is not implemented yet: it needs the recorded no-RETURNING \
                     divergences (last_insert_id + keyed re-SELECT) rather than a copy of the \
                     RETURNING path"
                        .to_owned(),
                ));
            }
        };
        Ok(Dial { krate })
    }
}

/// Render every generated file: `mod.rs` plus one file per model, as
/// `(file name, contents)` pairs sorted by file name.
pub(crate) fn render(models: &[Model], config: &Config) -> Result<Vec<(String, String)>> {
    let dial = Dial::new(config.dialect)?;
    let mut files = Vec::with_capacity(models.len() + 1);
    files.push(("mod.rs".to_owned(), render_mod_rs(models)));
    for m in models {
        let tokens = model::model_file(m, models, config, &dial)?;
        files.push((format!("{}.rs", m.table), render_file(tokens)?));
    }
    Ok(files)
}

fn render_mod_rs(models: &[Model]) -> String {
    let mut out = String::from(HEADER);
    out.push_str("\n//! The generated models, one module per table.\n\n");
    for m in models {
        let module = crate::names::ident(&m.table);
        out.push_str(&format!("pub mod {module};\n"));
    }
    out
}

fn render_file(tokens: TokenStream) -> Result<String> {
    let file: syn::File = syn::parse2(tokens)
        .map_err(|e| GenError::Config(format!("internal: generated tokens do not parse: {e}")))?;
    Ok(format!("{HEADER}\n{}", prettyplease::unparse(&file)))
}
