//! `--check`'s seam: [`keelson_gen::check_files`] must agree with
//! [`keelson_gen::write_files`] about every file, in both directions.
//!
//! The pair is a contract, not two functions: `check` exists to answer "would
//! `write` change anything?", so the only bug worth testing for is one where
//! the two disagree. Every case below therefore states the disagreement it
//! rules out.

use std::path::{Path, PathBuf};

use keelson_gen::Drift;

const HEADER: &str = "// @generated by keelson-gen. DO NOT EDIT.\n";

fn files(pairs: &[(&str, &str)]) -> Vec<(String, String)> {
    pairs
        .iter()
        .map(|(n, c)| ((*n).to_owned(), format!("{HEADER}{c}")))
        .collect()
}

/// A directory of its own per test — these write, and a shared one would make
/// them order-dependent.
fn temp_dir(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("keelson-gen-check-{}-{name}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("creating the temporary output directory");
    dir
}

#[test]
fn a_directory_that_write_files_just_wrote_has_no_drift() {
    let dir = temp_dir("fresh");
    let files = files(&[("mod.rs", "pub mod users;\n"), ("users.rs", "// users\n")]);
    keelson_gen::write_files(&dir, &files).expect("writing");

    assert_eq!(
        keelson_gen::check_files(&dir, &files).expect("checking"),
        vec![],
        "check must not report drift in a tree write_files just produced"
    );
}

#[test]
fn a_missing_output_directory_is_every_file_missing_and_not_an_error() {
    // `--check` runs in a checkout that may never have generated anything —
    // reporting the absent directory as an io error would make the first run
    // of the flag look like a broken configuration.
    let dir = temp_dir("absent");
    std::fs::remove_dir_all(&dir).expect("removing it again");
    let files = files(&[("mod.rs", "pub mod users;\n"), ("users.rs", "// users\n")]);

    assert_eq!(
        keelson_gen::check_files(&dir, &files).expect("checking"),
        vec![
            Drift::Missing(dir.join("mod.rs")),
            Drift::Missing(dir.join("users.rs")),
        ]
    );
}

#[test]
fn a_file_whose_contents_moved_is_stale_not_missing() {
    let dir = temp_dir("stale");
    let committed = files(&[("users.rs", "// old\n")]);
    keelson_gen::write_files(&dir, &committed).expect("writing");

    let rendered = files(&[("users.rs", "// new\n")]);
    assert_eq!(
        keelson_gen::check_files(&dir, &rendered).expect("checking"),
        vec![Drift::Stale(dir.join("users.rs"))]
    );
}

#[test]
fn a_generated_file_the_generator_dropped_is_orphaned_because_write_would_delete_it() {
    let dir = temp_dir("orphan");
    keelson_gen::write_files(
        &dir,
        &files(&[("users.rs", "// users\n"), ("posts.rs", "// posts\n")]),
    )
    .expect("writing");

    // The table went away: `posts.rs` is no longer rendered.
    let rendered = files(&[("users.rs", "// users\n")]);
    assert_eq!(
        keelson_gen::check_files(&dir, &rendered).expect("checking"),
        vec![Drift::Orphaned(dir.join("posts.rs"))]
    );

    // …and that is exactly what `write_files` does to it, which is the claim
    // the variant makes.
    keelson_gen::write_files(&dir, &rendered).expect("writing");
    assert!(!dir.join("posts.rs").exists());
    assert_eq!(
        keelson_gen::check_files(&dir, &rendered).expect("checking"),
        vec![]
    );
}

#[test]
fn a_hand_written_file_in_the_output_directory_is_neither_reported_nor_deleted() {
    // `write_files` only removes files carrying the `@generated` header. If
    // `check` were stricter, a `--check` job would demand a deletion that
    // regenerating does not perform — an unfixable failure.
    let dir = temp_dir("handwritten");
    let rendered = files(&[("users.rs", "// users\n")]);
    keelson_gen::write_files(&dir, &rendered).expect("writing");
    std::fs::write(dir.join("hooks.rs"), "// mine, not the generator's\n").expect("writing");

    assert_eq!(
        keelson_gen::check_files(&dir, &rendered).expect("checking"),
        vec![]
    );
    keelson_gen::write_files(&dir, &rendered).expect("writing");
    assert!(dir.join("hooks.rs").exists());
}

#[test]
fn drift_is_reported_in_path_order_so_a_ci_log_is_diffable() {
    let dir = temp_dir("order");
    keelson_gen::write_files(&dir, &files(&[("b.rs", "// b\n"), ("c.rs", "// c\n")]))
        .expect("writing");
    let rendered = files(&[("c.rs", "// changed\n"), ("a.rs", "// a\n")]);

    let drift = keelson_gen::check_files(&dir, &rendered).expect("checking");
    let paths: Vec<&Path> = drift.iter().map(Drift::path).collect();
    assert_eq!(
        paths,
        vec![
            dir.join("a.rs").as_path(),
            dir.join("b.rs").as_path(),
            dir.join("c.rs").as_path(),
        ]
    );
}
