// @generated by keelson-gen. DO NOT EDIT.
// Regenerate from the schema instead; hand-written code (hooks included)
// belongs outside this directory.

/// The model marker `audit_logs::table()` hangs off.
#[derive(Debug, Clone, Copy)]
pub struct AuditLogs;
/// One row of `audit_logs`.
#[derive(Debug, Clone, PartialEq)]
pub struct AuditLog {
    pub id: i64,
    pub entity: String,
    pub entity_id: i64,
    pub note: String,
    /// Relations, filled by `preload`/`then_load` mods; empty otherwise.
    pub rel: Rel,
}
/// `audit_logs`' relations.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Rel {}
impl keelson_exec::FromRow for AuditLog {
    fn from_row(row: &mut keelson_exec::Row) -> Result<Self, keelson_exec::ExecError> {
        Ok(AuditLog {
            id: row.take("id")?,
            entity: row.take("entity")?,
            entity_id: row.take("entity_id")?,
            note: row.take("note")?,
            rel: Rel::default(),
        })
    }
}
/// The three-state setter: unset fields stay out of the statement.
#[derive(Debug, Clone, Default)]
pub struct Setter {
    pub id: keelson_models::Set<i64>,
    pub entity: keelson_models::Set<String>,
    pub entity_id: keelson_models::Set<i64>,
    pub note: keelson_models::Set<String>,
}
/// The entry point: `audit_logs::table().query(…)` / `.insert(…)` / ….
pub fn table() -> keelson_models::ModelTable<AuditLogs> {
    keelson_models::ModelTable::new()
}
pub fn id() -> keelson_models::Column<i64> {
    keelson_models::Column::new("audit_logs", "id")
}
pub fn entity() -> keelson_models::Column<String> {
    keelson_models::Column::new("audit_logs", "entity")
}
pub fn entity_id() -> keelson_models::Column<i64> {
    keelson_models::Column::new("audit_logs", "entity_id")
}
pub fn note() -> keelson_models::Column<String> {
    keelson_models::Column::new("audit_logs", "note")
}
#[allow(clippy::type_complexity)]
fn all_columns() -> (
    keelson_models::Column<i64>,
    keelson_models::Column<String>,
    keelson_models::Column<i64>,
    keelson_models::Column<String>,
) {
    (id(), entity(), entity_id(), note())
}
impl keelson_models::View for AuditLogs {
    type Row = AuditLog;
    type Select = keelson_sqlite::SelectQuery;
    fn base_select() -> Self::Select {
        keelson_sqlite::select((
            keelson_sqlite::select::columns(all_columns()),
            keelson_sqlite::select::from(keelson_sqlite::quote("audit_logs")),
        ))
    }
}
impl keelson_models::Table for AuditLogs {
    type Pk = i64;
    type Setter = Setter;
    type Insert = keelson_sqlite::InsertQuery;
    type Update = keelson_sqlite::UpdateQuery;
    type Delete = keelson_sqlite::DeleteQuery;
    fn insert_query(s: Setter) -> Self::Insert {
        let mut cols: Vec<&'static str> = Vec::new();
        let mut vals: Vec<keelson_core::expr::Expr> = Vec::new();
        s.id.push_into("id", &mut cols, &mut vals);
        s.entity.push_into("entity", &mut cols, &mut vals);
        s.entity_id.push_into("entity_id", &mut cols, &mut vals);
        s.note.push_into("note", &mut cols, &mut vals);
        let mut q = keelson_sqlite::insert((
            keelson_sqlite::insert::into(keelson_sqlite::quote("audit_logs"))
                .columns(cols),
            keelson_sqlite::insert::returning(all_columns()),
        ));
        if !vals.is_empty() {
            q.apply(keelson_sqlite::insert::values(vals));
        }
        q
    }
    fn update_query() -> Self::Update {
        keelson_sqlite::update(
            keelson_sqlite::update::table(keelson_sqlite::quote("audit_logs")),
        )
    }
    fn apply_setter(s: Setter, q: &mut Self::Update) {
        if let Some(v) = s.id.into_expr() {
            q.apply(keelson_sqlite::update::set_col("id").to(v));
        }
        if let Some(v) = s.entity.into_expr() {
            q.apply(keelson_sqlite::update::set_col("entity").to(v));
        }
        if let Some(v) = s.entity_id.into_expr() {
            q.apply(keelson_sqlite::update::set_col("entity_id").to(v));
        }
        if let Some(v) = s.note.into_expr() {
            q.apply(keelson_sqlite::update::set_col("note").to(v));
        }
    }
    fn delete_query() -> Self::Delete {
        keelson_sqlite::delete(
            keelson_sqlite::delete::from(keelson_sqlite::quote("audit_logs")),
        )
    }
    fn pk(row: &AuditLog) -> Self::Pk {
        row.id
    }
}
