// @generated by keelson-gen. DO NOT EDIT.
// Regenerate from the schema instead; hand-written code (hooks included)
// belongs outside this directory.

/// The `audit_logs` factory.
pub mod audit_logs {
    /// The model's uniqueness source: one process-wide sequence.
    static SEQ: keelson_factory::Sequence = keelson_factory::Sequence::new();
    /// The `audit_logs` template: one value source per column.
    #[derive(Debug, Clone, Default)]
    pub struct AuditLogTemplate {
        /// `id`.
        pub id: keelson_factory::Source<i64>,
        /// `entity`.
        pub entity: keelson_factory::Source<String>,
        /// `entity_id`.
        pub entity_id: keelson_factory::Source<i64>,
        /// `note`.
        pub note: keelson_factory::Source<String>,
    }
    /// The entry point: `factory((id(10), …))`.
    pub fn factory(mods: impl keelson_core::Mod<AuditLogTemplate>) -> AuditLogTemplate {
        let mut t = AuditLogTemplate::default();
        mods.apply(&mut t);
        t
    }
    /// Set `id`.
    pub fn id(v: i64) -> impl keelson_core::Mod<AuditLogTemplate> {
        keelson_core::mod_fn(move |t: &mut AuditLogTemplate| {
            t.id = keelson_factory::Source::Value(v)
        })
    }
    /// Draw `id` at random instead of from the sequence — random values are inside the faker's seed, sequence values deliberately are not.
    pub fn random_id() -> impl keelson_core::Mod<AuditLogTemplate> {
        keelson_core::mod_fn(|t: &mut AuditLogTemplate| {
            t.id = keelson_factory::Source::from_fn(|f| f.i64_in(1, i64::MAX / 2))
        })
    }
    /// Set `entity`.
    pub fn entity(v: impl Into<String>) -> impl keelson_core::Mod<AuditLogTemplate> {
        let v = v.into();
        keelson_core::mod_fn(move |t: &mut AuditLogTemplate| {
            t.entity = keelson_factory::Source::Value(v)
        })
    }
    /// Set `entity_id`.
    pub fn entity_id(v: i64) -> impl keelson_core::Mod<AuditLogTemplate> {
        keelson_core::mod_fn(move |t: &mut AuditLogTemplate| {
            t.entity_id = keelson_factory::Source::Value(v)
        })
    }
    /// Set `note`.
    pub fn note(v: impl Into<String>) -> impl keelson_core::Mod<AuditLogTemplate> {
        let v = v.into();
        keelson_core::mod_fn(move |t: &mut AuditLogTemplate| {
            t.note = keelson_factory::Source::Value(v)
        })
    }
    impl AuditLogTemplate {
        /// The no-database strategy: the setter `create` would insert. No executor in the signature — that absence is the guarantee.
        pub fn build(
            &self,
            f: &mut keelson_factory::Faker,
        ) -> super::super::audit_logs::Setter {
            super::super::audit_logs::Setter {
                id: self.id.resolve(f, |_| keelson_models::Set::Value(SEQ.next_i64())),
                entity: self
                    .entity
                    .resolve(
                        f,
                        |f| keelson_models::Set::Value(
                            format!("audit_log-{}", f.alnum(8)),
                        ),
                    ),
                entity_id: self
                    .entity_id
                    .resolve(f, |f| keelson_models::Set::Value(f.i64_in(1, 1000))),
                note: self
                    .note
                    .resolve(
                        f,
                        |f| keelson_models::Set::Value(
                            format!("audit_log-{}", f.alnum(8)),
                        ),
                    ),
            }
        }
        /// Create the parent chain (unless overridden), the row itself through the model's own insert path — so hooks fire — and then the queued children. Boxed rather than an `async fn` because factory graphs recurse.
        pub fn create_with<'a>(
            &'a self,
            db: &'a dyn keelson_exec::Executor,
            f: &'a mut keelson_factory::Faker,
        ) -> keelson_exec::ExecFuture<
            'a,
            Result<super::super::audit_logs::AuditLog, keelson_exec::ExecError>,
        > {
            Box::pin(async move {
                let s = self.build(f);
                super::super::audit_logs::table().insert(s).one(db).await
            })
        }
        /// Create one row (and whatever parents and children the template implies) with a fresh entropy-seeded faker.
        pub async fn create(
            &self,
            db: &dyn keelson_exec::Executor,
        ) -> Result<super::super::audit_logs::AuditLog, keelson_exec::ExecError> {
            let mut f = keelson_factory::Faker::from_entropy();
            self.create_with(db, &mut f).await
        }
        /// Create `n` rows; sequences keep the unique columns apart.
        pub async fn create_many(
            &self,
            db: &dyn keelson_exec::Executor,
            n: usize,
        ) -> Result<Vec<super::super::audit_logs::AuditLog>, keelson_exec::ExecError> {
            let mut f = keelson_factory::Faker::from_entropy();
            let mut out = Vec::with_capacity(n);
            for _ in 0..n {
                out.push(self.create_with(db, &mut f).await?);
            }
            Ok(out)
        }
    }
}
/// The `comments` factory.
pub mod comments {
    /// The model's uniqueness source: one process-wide sequence.
    static SEQ: keelson_factory::Sequence = keelson_factory::Sequence::new();
    /// The `comments` template: one value source per column.
    #[derive(Debug, Clone, Default)]
    pub struct CommentTemplate {
        /// `id`.
        pub id: keelson_factory::Source<i64>,
        /// FK `post_id` → `posts`: auto-created from `posts`'s own template unless a mod overrides it.
        pub post: keelson_factory::Parent<Box<super::posts::PostTemplate>, i64>,
        /// Nullable FK `user_id` → `users`: absent (NULL) unless a mod opts in.
        pub user: keelson_factory::OptionalParent<Box<super::users::UserTemplate>, i64>,
        /// `body`.
        pub body: keelson_factory::Source<String>,
        /// `created_at`.
        pub created_at: keelson_factory::Source<chrono::NaiveDateTime>,
    }
    /// The entry point: `factory((id(10), …))`.
    pub fn factory(mods: impl keelson_core::Mod<CommentTemplate>) -> CommentTemplate {
        let mut t = CommentTemplate::default();
        mods.apply(&mut t);
        t
    }
    /// Set `id`.
    pub fn id(v: i64) -> impl keelson_core::Mod<CommentTemplate> {
        keelson_core::mod_fn(move |t: &mut CommentTemplate| {
            t.id = keelson_factory::Source::Value(v)
        })
    }
    /// Draw `id` at random instead of from the sequence — random values are inside the faker's seed, sequence values deliberately are not.
    pub fn random_id() -> impl keelson_core::Mod<CommentTemplate> {
        keelson_core::mod_fn(|t: &mut CommentTemplate| {
            t.id = keelson_factory::Source::from_fn(|f| f.i64_in(1, i64::MAX / 2))
        })
    }
    /// Use this existing `posts` row as the parent.
    pub fn post(
        row: &super::super::posts::Post,
    ) -> impl keelson_core::Mod<CommentTemplate> {
        let pk = row.id;
        keelson_core::mod_fn(move |t: &mut CommentTemplate| {
            t.post = keelson_factory::Parent::Existing(pk);
        })
    }
    /// Use this existing `posts` key as the parent.
    pub fn post_id(pk: i64) -> impl keelson_core::Mod<CommentTemplate> {
        keelson_core::mod_fn(move |t: &mut CommentTemplate| {
            t.post = keelson_factory::Parent::Existing(pk);
        })
    }
    /// Create the `posts` parent from this template.
    pub fn for_post(
        tpl: super::posts::PostTemplate,
    ) -> impl keelson_core::Mod<CommentTemplate> {
        keelson_core::mod_fn(move |t: &mut CommentTemplate| {
            t.post = keelson_factory::Parent::Template(Box::new(tpl))
        })
    }
    /// Use this existing `users` row as the parent.
    pub fn user(
        row: &super::super::users::User,
    ) -> impl keelson_core::Mod<CommentTemplate> {
        let pk = row.id;
        keelson_core::mod_fn(move |t: &mut CommentTemplate| {
            t.user = keelson_factory::OptionalParent::Existing(pk);
        })
    }
    /// Use this existing `users` key as the parent.
    pub fn user_id(pk: i64) -> impl keelson_core::Mod<CommentTemplate> {
        keelson_core::mod_fn(move |t: &mut CommentTemplate| {
            t.user = keelson_factory::OptionalParent::Existing(pk);
        })
    }
    /// Create the `users` parent from this template.
    pub fn for_user(
        tpl: super::users::UserTemplate,
    ) -> impl keelson_core::Mod<CommentTemplate> {
        keelson_core::mod_fn(move |t: &mut CommentTemplate| {
            t.user = keelson_factory::OptionalParent::Template(Box::new(tpl))
        })
    }
    /// Set `body`.
    pub fn body(v: impl Into<String>) -> impl keelson_core::Mod<CommentTemplate> {
        let v = v.into();
        keelson_core::mod_fn(move |t: &mut CommentTemplate| {
            t.body = keelson_factory::Source::Value(v)
        })
    }
    /// Set `created_at`.
    pub fn created_at(
        v: chrono::NaiveDateTime,
    ) -> impl keelson_core::Mod<CommentTemplate> {
        keelson_core::mod_fn(move |t: &mut CommentTemplate| {
            t.created_at = keelson_factory::Source::Value(v)
        })
    }
    impl CommentTemplate {
        /// The no-database strategy: the setter `create` would insert. No executor in the signature — that absence is the guarantee.
        pub fn build(
            &self,
            f: &mut keelson_factory::Faker,
        ) -> super::super::comments::Setter {
            super::super::comments::Setter {
                id: self.id.resolve(f, |_| keelson_models::Set::Value(SEQ.next_i64())),
                post_id: match &self.post {
                    keelson_factory::Parent::Existing(pk) => {
                        keelson_models::Set::Value(*pk)
                    }
                    keelson_factory::Parent::Auto
                    | keelson_factory::Parent::Template(_) => keelson_models::Set::Unset,
                },
                user_id: match &self.user {
                    keelson_factory::OptionalParent::Existing(pk) => {
                        keelson_models::Set::Value(*pk)
                    }
                    keelson_factory::OptionalParent::Absent
                    | keelson_factory::OptionalParent::Template(_) => {
                        keelson_models::Set::Unset
                    }
                },
                body: self
                    .body
                    .resolve(
                        f,
                        |f| keelson_models::Set::Value(format!("comment-{}", f.alnum(8))),
                    ),
                created_at: self.created_at.resolve(f, |_| keelson_models::Set::Unset),
            }
        }
        /// Create the parent chain (unless overridden), the row itself through the model's own insert path — so hooks fire — and then the queued children. Boxed rather than an `async fn` because factory graphs recurse.
        pub fn create_with<'a>(
            &'a self,
            db: &'a dyn keelson_exec::Executor,
            f: &'a mut keelson_factory::Faker,
        ) -> keelson_exec::ExecFuture<
            'a,
            Result<super::super::comments::Comment, keelson_exec::ExecError>,
        > {
            Box::pin(async move {
                let mut s = self.build(f);
                match &self.post {
                    keelson_factory::Parent::Existing(_) => {}
                    keelson_factory::Parent::Template(t) => {
                        s.post_id = keelson_models::Set::Value(
                            t.create_with(db, &mut *f).await?.id,
                        );
                    }
                    keelson_factory::Parent::Auto => {
                        let t = super::posts::PostTemplate::default();
                        s.post_id = keelson_models::Set::Value(
                            t.create_with(db, &mut *f).await?.id,
                        );
                    }
                }
                if let keelson_factory::OptionalParent::Template(t) = &self.user {
                    s.user_id = keelson_models::Set::Value(
                        t.create_with(db, &mut *f).await?.id,
                    );
                }
                super::super::comments::table().insert(s).one(db).await
            })
        }
        /// Create one row (and whatever parents and children the template implies) with a fresh entropy-seeded faker.
        pub async fn create(
            &self,
            db: &dyn keelson_exec::Executor,
        ) -> Result<super::super::comments::Comment, keelson_exec::ExecError> {
            let mut f = keelson_factory::Faker::from_entropy();
            self.create_with(db, &mut f).await
        }
        /// Create `n` rows; sequences keep the unique columns apart.
        pub async fn create_many(
            &self,
            db: &dyn keelson_exec::Executor,
            n: usize,
        ) -> Result<Vec<super::super::comments::Comment>, keelson_exec::ExecError> {
            let mut f = keelson_factory::Faker::from_entropy();
            let mut out = Vec::with_capacity(n);
            for _ in 0..n {
                out.push(self.create_with(db, &mut f).await?);
            }
            Ok(out)
        }
    }
}
/// The `post_tags` factory.
pub mod post_tags {
    /// The `post_tags` template: one value source per column.
    #[derive(Debug, Clone, Default)]
    pub struct PostTagTemplate {
        /// FK `post_id` → `posts`: auto-created from `posts`'s own template unless a mod overrides it.
        pub post: keelson_factory::Parent<Box<super::posts::PostTemplate>, i64>,
        /// FK `tag_id` → `tags`: auto-created from `tags`'s own template unless a mod overrides it.
        pub tag: keelson_factory::Parent<Box<super::tags::TagTemplate>, i64>,
    }
    /// The entry point: `factory((id(10), …))`.
    pub fn factory(mods: impl keelson_core::Mod<PostTagTemplate>) -> PostTagTemplate {
        let mut t = PostTagTemplate::default();
        mods.apply(&mut t);
        t
    }
    /// Use this existing `posts` row as the parent.
    pub fn post(
        row: &super::super::posts::Post,
    ) -> impl keelson_core::Mod<PostTagTemplate> {
        let pk = row.id;
        keelson_core::mod_fn(move |t: &mut PostTagTemplate| {
            t.post = keelson_factory::Parent::Existing(pk);
        })
    }
    /// Use this existing `posts` key as the parent.
    pub fn post_id(pk: i64) -> impl keelson_core::Mod<PostTagTemplate> {
        keelson_core::mod_fn(move |t: &mut PostTagTemplate| {
            t.post = keelson_factory::Parent::Existing(pk);
        })
    }
    /// Create the `posts` parent from this template.
    pub fn for_post(
        tpl: super::posts::PostTemplate,
    ) -> impl keelson_core::Mod<PostTagTemplate> {
        keelson_core::mod_fn(move |t: &mut PostTagTemplate| {
            t.post = keelson_factory::Parent::Template(Box::new(tpl))
        })
    }
    /// Use this existing `tags` row as the parent.
    pub fn tag(
        row: &super::super::tags::Tag,
    ) -> impl keelson_core::Mod<PostTagTemplate> {
        let pk = row.id;
        keelson_core::mod_fn(move |t: &mut PostTagTemplate| {
            t.tag = keelson_factory::Parent::Existing(pk);
        })
    }
    /// Use this existing `tags` key as the parent.
    pub fn tag_id(pk: i64) -> impl keelson_core::Mod<PostTagTemplate> {
        keelson_core::mod_fn(move |t: &mut PostTagTemplate| {
            t.tag = keelson_factory::Parent::Existing(pk);
        })
    }
    /// Create the `tags` parent from this template.
    pub fn for_tag(
        tpl: super::tags::TagTemplate,
    ) -> impl keelson_core::Mod<PostTagTemplate> {
        keelson_core::mod_fn(move |t: &mut PostTagTemplate| {
            t.tag = keelson_factory::Parent::Template(Box::new(tpl))
        })
    }
    impl PostTagTemplate {
        /// The no-database strategy: the setter `create` would insert. No executor in the signature — that absence is the guarantee.
        pub fn build(
            &self,
            _f: &mut keelson_factory::Faker,
        ) -> super::super::post_tags::Setter {
            super::super::post_tags::Setter {
                post_id: match &self.post {
                    keelson_factory::Parent::Existing(pk) => {
                        keelson_models::Set::Value(*pk)
                    }
                    keelson_factory::Parent::Auto
                    | keelson_factory::Parent::Template(_) => keelson_models::Set::Unset,
                },
                tag_id: match &self.tag {
                    keelson_factory::Parent::Existing(pk) => {
                        keelson_models::Set::Value(*pk)
                    }
                    keelson_factory::Parent::Auto
                    | keelson_factory::Parent::Template(_) => keelson_models::Set::Unset,
                },
            }
        }
        /// Create the parent chain (unless overridden), the row itself through the model's own insert path — so hooks fire — and then the queued children. Boxed rather than an `async fn` because factory graphs recurse.
        pub fn create_with<'a>(
            &'a self,
            db: &'a dyn keelson_exec::Executor,
            f: &'a mut keelson_factory::Faker,
        ) -> keelson_exec::ExecFuture<
            'a,
            Result<super::super::post_tags::PostTag, keelson_exec::ExecError>,
        > {
            Box::pin(async move {
                let mut s = self.build(f);
                match &self.post {
                    keelson_factory::Parent::Existing(_) => {}
                    keelson_factory::Parent::Template(t) => {
                        s.post_id = keelson_models::Set::Value(
                            t.create_with(db, &mut *f).await?.id,
                        );
                    }
                    keelson_factory::Parent::Auto => {
                        let t = super::posts::PostTemplate::default();
                        s.post_id = keelson_models::Set::Value(
                            t.create_with(db, &mut *f).await?.id,
                        );
                    }
                }
                match &self.tag {
                    keelson_factory::Parent::Existing(_) => {}
                    keelson_factory::Parent::Template(t) => {
                        s.tag_id = keelson_models::Set::Value(
                            t.create_with(db, &mut *f).await?.id,
                        );
                    }
                    keelson_factory::Parent::Auto => {
                        let t = super::tags::TagTemplate::default();
                        s.tag_id = keelson_models::Set::Value(
                            t.create_with(db, &mut *f).await?.id,
                        );
                    }
                }
                super::super::post_tags::table().insert(s).one(db).await
            })
        }
        /// Create one row (and whatever parents and children the template implies) with a fresh entropy-seeded faker.
        pub async fn create(
            &self,
            db: &dyn keelson_exec::Executor,
        ) -> Result<super::super::post_tags::PostTag, keelson_exec::ExecError> {
            let mut f = keelson_factory::Faker::from_entropy();
            self.create_with(db, &mut f).await
        }
        /// Create `n` rows; sequences keep the unique columns apart.
        pub async fn create_many(
            &self,
            db: &dyn keelson_exec::Executor,
            n: usize,
        ) -> Result<Vec<super::super::post_tags::PostTag>, keelson_exec::ExecError> {
            let mut f = keelson_factory::Faker::from_entropy();
            let mut out = Vec::with_capacity(n);
            for _ in 0..n {
                out.push(self.create_with(db, &mut f).await?);
            }
            Ok(out)
        }
    }
}
/// The `posts` factory.
pub mod posts {
    /// The model's uniqueness source: one process-wide sequence.
    static SEQ: keelson_factory::Sequence = keelson_factory::Sequence::new();
    /// The `posts` template: one value source per column.
    #[derive(Debug, Clone, Default)]
    pub struct PostTemplate {
        /// `id`.
        pub id: keelson_factory::Source<i64>,
        /// FK `user_id` → `users`: auto-created from `users`'s own template unless a mod overrides it.
        pub user: keelson_factory::Parent<Box<super::users::UserTemplate>, i64>,
        /// `title`.
        pub title: keelson_factory::Source<String>,
        /// `status`.
        pub status: keelson_factory::Source<String>,
        /// `views`.
        pub views: keelson_factory::Source<i64>,
        /// `published_at`.
        pub published_at: keelson_factory::Source<chrono::NaiveDateTime>,
        /// Has-many `comments` children, created after this row exists, each with `comments.post_id` forced to it.
        pub comments: Vec<super::comments::CommentTemplate>,
        /// Has-many `post_tags` children, created after this row exists, each with `post_tags.post_id` forced to it.
        pub post_tags: Vec<super::post_tags::PostTagTemplate>,
    }
    /// The entry point: `factory((id(10), …))`.
    pub fn factory(mods: impl keelson_core::Mod<PostTemplate>) -> PostTemplate {
        let mut t = PostTemplate::default();
        mods.apply(&mut t);
        t
    }
    /// Set `id`.
    pub fn id(v: i64) -> impl keelson_core::Mod<PostTemplate> {
        keelson_core::mod_fn(move |t: &mut PostTemplate| {
            t.id = keelson_factory::Source::Value(v)
        })
    }
    /// Draw `id` at random instead of from the sequence — random values are inside the faker's seed, sequence values deliberately are not.
    pub fn random_id() -> impl keelson_core::Mod<PostTemplate> {
        keelson_core::mod_fn(|t: &mut PostTemplate| {
            t.id = keelson_factory::Source::from_fn(|f| f.i64_in(1, i64::MAX / 2))
        })
    }
    /// Use this existing `users` row as the parent.
    pub fn user(
        row: &super::super::users::User,
    ) -> impl keelson_core::Mod<PostTemplate> {
        let pk = row.id;
        keelson_core::mod_fn(move |t: &mut PostTemplate| {
            t.user = keelson_factory::Parent::Existing(pk);
        })
    }
    /// Use this existing `users` key as the parent.
    pub fn user_id(pk: i64) -> impl keelson_core::Mod<PostTemplate> {
        keelson_core::mod_fn(move |t: &mut PostTemplate| {
            t.user = keelson_factory::Parent::Existing(pk);
        })
    }
    /// Create the `users` parent from this template.
    pub fn for_user(
        tpl: super::users::UserTemplate,
    ) -> impl keelson_core::Mod<PostTemplate> {
        keelson_core::mod_fn(move |t: &mut PostTemplate| {
            t.user = keelson_factory::Parent::Template(Box::new(tpl))
        })
    }
    /// Set `title`.
    pub fn title(v: impl Into<String>) -> impl keelson_core::Mod<PostTemplate> {
        let v = v.into();
        keelson_core::mod_fn(move |t: &mut PostTemplate| {
            t.title = keelson_factory::Source::Value(v)
        })
    }
    /// Set `status`.
    pub fn status(v: impl Into<String>) -> impl keelson_core::Mod<PostTemplate> {
        let v = v.into();
        keelson_core::mod_fn(move |t: &mut PostTemplate| {
            t.status = keelson_factory::Source::Value(v)
        })
    }
    /// Set `status` to SQL NULL.
    pub fn status_null() -> impl keelson_core::Mod<PostTemplate> {
        keelson_core::mod_fn(|t: &mut PostTemplate| {
            t.status = keelson_factory::Source::Null
        })
    }
    /// Set `views`.
    pub fn views(v: i64) -> impl keelson_core::Mod<PostTemplate> {
        keelson_core::mod_fn(move |t: &mut PostTemplate| {
            t.views = keelson_factory::Source::Value(v)
        })
    }
    /// Set `published_at`.
    pub fn published_at(
        v: chrono::NaiveDateTime,
    ) -> impl keelson_core::Mod<PostTemplate> {
        keelson_core::mod_fn(move |t: &mut PostTemplate| {
            t.published_at = keelson_factory::Source::Value(v)
        })
    }
    /// Set `published_at` to SQL NULL.
    pub fn published_at_null() -> impl keelson_core::Mod<PostTemplate> {
        keelson_core::mod_fn(|t: &mut PostTemplate| {
            t.published_at = keelson_factory::Source::Null
        })
    }
    /// Queue a new `comments` child for this row.
    pub fn with_new_comment(
        tpl: super::comments::CommentTemplate,
    ) -> impl keelson_core::Mod<PostTemplate> {
        keelson_core::mod_fn(move |t: &mut PostTemplate| t.comments.push(tpl))
    }
    /// Queue a new `post_tags` child for this row.
    pub fn with_new_post_tag(
        tpl: super::post_tags::PostTagTemplate,
    ) -> impl keelson_core::Mod<PostTemplate> {
        keelson_core::mod_fn(move |t: &mut PostTemplate| t.post_tags.push(tpl))
    }
    impl PostTemplate {
        /// The no-database strategy: the setter `create` would insert. No executor in the signature — that absence is the guarantee.
        pub fn build(
            &self,
            f: &mut keelson_factory::Faker,
        ) -> super::super::posts::Setter {
            super::super::posts::Setter {
                id: self.id.resolve(f, |_| keelson_models::Set::Value(SEQ.next_i64())),
                user_id: match &self.user {
                    keelson_factory::Parent::Existing(pk) => {
                        keelson_models::Set::Value(*pk)
                    }
                    keelson_factory::Parent::Auto
                    | keelson_factory::Parent::Template(_) => keelson_models::Set::Unset,
                },
                title: self
                    .title
                    .resolve(
                        f,
                        |f| keelson_models::Set::Value(format!("post-{}", f.alnum(8))),
                    ),
                status: self
                    .status
                    .resolve(
                        f,
                        |f| keelson_models::Set::Value(format!("post-{}", f.alnum(8))),
                    ),
                views: self.views.resolve(f, |_| keelson_models::Set::Unset),
                published_at: self
                    .published_at
                    .resolve(f, |_| keelson_models::Set::Unset),
            }
        }
        /// Create the parent chain (unless overridden), the row itself through the model's own insert path — so hooks fire — and then the queued children. Boxed rather than an `async fn` because factory graphs recurse.
        pub fn create_with<'a>(
            &'a self,
            db: &'a dyn keelson_exec::Executor,
            f: &'a mut keelson_factory::Faker,
        ) -> keelson_exec::ExecFuture<
            'a,
            Result<super::super::posts::Post, keelson_exec::ExecError>,
        > {
            Box::pin(async move {
                let mut s = self.build(f);
                match &self.user {
                    keelson_factory::Parent::Existing(_) => {}
                    keelson_factory::Parent::Template(t) => {
                        s.user_id = keelson_models::Set::Value(
                            t.create_with(db, &mut *f).await?.id,
                        );
                    }
                    keelson_factory::Parent::Auto => {
                        let t = super::users::UserTemplate::default();
                        s.user_id = keelson_models::Set::Value(
                            t.create_with(db, &mut *f).await?.id,
                        );
                    }
                }
                let row = super::super::posts::table().insert(s).one(db).await?;
                for c in &self.comments {
                    let mut child = c.clone();
                    child.post = keelson_factory::Parent::Existing(row.id);
                    child.create_with(db, &mut *f).await?;
                }
                for c in &self.post_tags {
                    let mut child = c.clone();
                    child.post = keelson_factory::Parent::Existing(row.id);
                    child.create_with(db, &mut *f).await?;
                }
                Ok(row)
            })
        }
        /// Create one row (and whatever parents and children the template implies) with a fresh entropy-seeded faker.
        pub async fn create(
            &self,
            db: &dyn keelson_exec::Executor,
        ) -> Result<super::super::posts::Post, keelson_exec::ExecError> {
            let mut f = keelson_factory::Faker::from_entropy();
            self.create_with(db, &mut f).await
        }
        /// Create `n` rows; sequences keep the unique columns apart.
        pub async fn create_many(
            &self,
            db: &dyn keelson_exec::Executor,
            n: usize,
        ) -> Result<Vec<super::super::posts::Post>, keelson_exec::ExecError> {
            let mut f = keelson_factory::Faker::from_entropy();
            let mut out = Vec::with_capacity(n);
            for _ in 0..n {
                out.push(self.create_with(db, &mut f).await?);
            }
            Ok(out)
        }
    }
}
/// The `tags` factory.
pub mod tags {
    /// The model's uniqueness source: one process-wide sequence.
    static SEQ: keelson_factory::Sequence = keelson_factory::Sequence::new();
    /// The `tags` template: one value source per column.
    #[derive(Debug, Clone, Default)]
    pub struct TagTemplate {
        /// `id`.
        pub id: keelson_factory::Source<i64>,
        /// `name`.
        pub name: keelson_factory::Source<String>,
        /// Has-many `post_tags` children, created after this row exists, each with `post_tags.tag_id` forced to it.
        pub post_tags: Vec<super::post_tags::PostTagTemplate>,
    }
    /// The entry point: `factory((id(10), …))`.
    pub fn factory(mods: impl keelson_core::Mod<TagTemplate>) -> TagTemplate {
        let mut t = TagTemplate::default();
        mods.apply(&mut t);
        t
    }
    /// Set `id`.
    pub fn id(v: i64) -> impl keelson_core::Mod<TagTemplate> {
        keelson_core::mod_fn(move |t: &mut TagTemplate| {
            t.id = keelson_factory::Source::Value(v)
        })
    }
    /// Draw `id` at random instead of from the sequence — random values are inside the faker's seed, sequence values deliberately are not.
    pub fn random_id() -> impl keelson_core::Mod<TagTemplate> {
        keelson_core::mod_fn(|t: &mut TagTemplate| {
            t.id = keelson_factory::Source::from_fn(|f| f.i64_in(1, i64::MAX / 2))
        })
    }
    /// Set `name`.
    pub fn name(v: impl Into<String>) -> impl keelson_core::Mod<TagTemplate> {
        let v = v.into();
        keelson_core::mod_fn(move |t: &mut TagTemplate| {
            t.name = keelson_factory::Source::Value(v)
        })
    }
    /// Draw `name` at random instead of from the sequence — random values are inside the faker's seed, sequence values deliberately are not.
    pub fn random_name() -> impl keelson_core::Mod<TagTemplate> {
        keelson_core::mod_fn(|t: &mut TagTemplate| {
            t.name = keelson_factory::Source::from_fn(|f| f.alnum(12))
        })
    }
    /// Queue a new `post_tags` child for this row.
    pub fn with_new_post_tag(
        tpl: super::post_tags::PostTagTemplate,
    ) -> impl keelson_core::Mod<TagTemplate> {
        keelson_core::mod_fn(move |t: &mut TagTemplate| t.post_tags.push(tpl))
    }
    impl TagTemplate {
        /// The no-database strategy: the setter `create` would insert. No executor in the signature — that absence is the guarantee.
        pub fn build(
            &self,
            f: &mut keelson_factory::Faker,
        ) -> super::super::tags::Setter {
            super::super::tags::Setter {
                id: self.id.resolve(f, |_| keelson_models::Set::Value(SEQ.next_i64())),
                name: self
                    .name
                    .resolve(
                        f,
                        |_| keelson_models::Set::Value(format!("tag-{}", SEQ.next_i32())),
                    ),
            }
        }
        /// Create the parent chain (unless overridden), the row itself through the model's own insert path — so hooks fire — and then the queued children. Boxed rather than an `async fn` because factory graphs recurse.
        pub fn create_with<'a>(
            &'a self,
            db: &'a dyn keelson_exec::Executor,
            f: &'a mut keelson_factory::Faker,
        ) -> keelson_exec::ExecFuture<
            'a,
            Result<super::super::tags::Tag, keelson_exec::ExecError>,
        > {
            Box::pin(async move {
                let s = self.build(f);
                let row = super::super::tags::table().insert(s).one(db).await?;
                for c in &self.post_tags {
                    let mut child = c.clone();
                    child.tag = keelson_factory::Parent::Existing(row.id);
                    child.create_with(db, &mut *f).await?;
                }
                Ok(row)
            })
        }
        /// Create one row (and whatever parents and children the template implies) with a fresh entropy-seeded faker.
        pub async fn create(
            &self,
            db: &dyn keelson_exec::Executor,
        ) -> Result<super::super::tags::Tag, keelson_exec::ExecError> {
            let mut f = keelson_factory::Faker::from_entropy();
            self.create_with(db, &mut f).await
        }
        /// Create `n` rows; sequences keep the unique columns apart.
        pub async fn create_many(
            &self,
            db: &dyn keelson_exec::Executor,
            n: usize,
        ) -> Result<Vec<super::super::tags::Tag>, keelson_exec::ExecError> {
            let mut f = keelson_factory::Faker::from_entropy();
            let mut out = Vec::with_capacity(n);
            for _ in 0..n {
                out.push(self.create_with(db, &mut f).await?);
            }
            Ok(out)
        }
    }
}
/// The `users` factory.
pub mod users {
    /// The model's uniqueness source: one process-wide sequence.
    static SEQ: keelson_factory::Sequence = keelson_factory::Sequence::new();
    /// The `users` template: one value source per column.
    #[derive(Debug, Clone, Default)]
    pub struct UserTemplate {
        /// `id`.
        pub id: keelson_factory::Source<i64>,
        /// `name`.
        pub name: keelson_factory::Source<String>,
        /// `email`.
        pub email: keelson_factory::Source<String>,
        /// `age`.
        pub age: keelson_factory::Source<i64>,
        /// `is_active`.
        pub is_active: keelson_factory::Source<bool>,
        /// `created_at`.
        pub created_at: keelson_factory::Source<chrono::NaiveDateTime>,
        /// Has-many `comments` children, created after this row exists, each with `comments.user_id` forced to it.
        pub comments: Vec<super::comments::CommentTemplate>,
        /// Has-many `posts` children, created after this row exists, each with `posts.user_id` forced to it.
        pub posts: Vec<super::posts::PostTemplate>,
    }
    /// The entry point: `factory((id(10), …))`.
    pub fn factory(mods: impl keelson_core::Mod<UserTemplate>) -> UserTemplate {
        let mut t = UserTemplate::default();
        mods.apply(&mut t);
        t
    }
    /// Set `id`.
    pub fn id(v: i64) -> impl keelson_core::Mod<UserTemplate> {
        keelson_core::mod_fn(move |t: &mut UserTemplate| {
            t.id = keelson_factory::Source::Value(v)
        })
    }
    /// Draw `id` at random instead of from the sequence — random values are inside the faker's seed, sequence values deliberately are not.
    pub fn random_id() -> impl keelson_core::Mod<UserTemplate> {
        keelson_core::mod_fn(|t: &mut UserTemplate| {
            t.id = keelson_factory::Source::from_fn(|f| f.i64_in(1, i64::MAX / 2))
        })
    }
    /// Set `name`.
    pub fn name(v: impl Into<String>) -> impl keelson_core::Mod<UserTemplate> {
        let v = v.into();
        keelson_core::mod_fn(move |t: &mut UserTemplate| {
            t.name = keelson_factory::Source::Value(v)
        })
    }
    /// Set `email`.
    pub fn email(v: impl Into<String>) -> impl keelson_core::Mod<UserTemplate> {
        let v = v.into();
        keelson_core::mod_fn(move |t: &mut UserTemplate| {
            t.email = keelson_factory::Source::Value(v)
        })
    }
    /// Set `email` to SQL NULL.
    pub fn email_null() -> impl keelson_core::Mod<UserTemplate> {
        keelson_core::mod_fn(|t: &mut UserTemplate| {
            t.email = keelson_factory::Source::Null
        })
    }
    /// Set `age`.
    pub fn age(v: i64) -> impl keelson_core::Mod<UserTemplate> {
        keelson_core::mod_fn(move |t: &mut UserTemplate| {
            t.age = keelson_factory::Source::Value(v)
        })
    }
    /// Set `age` to SQL NULL.
    pub fn age_null() -> impl keelson_core::Mod<UserTemplate> {
        keelson_core::mod_fn(|t: &mut UserTemplate| {
            t.age = keelson_factory::Source::Null
        })
    }
    /// Set `is_active`.
    pub fn is_active(v: bool) -> impl keelson_core::Mod<UserTemplate> {
        keelson_core::mod_fn(move |t: &mut UserTemplate| {
            t.is_active = keelson_factory::Source::Value(v)
        })
    }
    /// Set `created_at`.
    pub fn created_at(v: chrono::NaiveDateTime) -> impl keelson_core::Mod<UserTemplate> {
        keelson_core::mod_fn(move |t: &mut UserTemplate| {
            t.created_at = keelson_factory::Source::Value(v)
        })
    }
    /// Queue a new `comments` child for this row.
    pub fn with_new_comment(
        tpl: super::comments::CommentTemplate,
    ) -> impl keelson_core::Mod<UserTemplate> {
        keelson_core::mod_fn(move |t: &mut UserTemplate| t.comments.push(tpl))
    }
    /// Queue a new `posts` child for this row.
    pub fn with_new_post(
        tpl: super::posts::PostTemplate,
    ) -> impl keelson_core::Mod<UserTemplate> {
        keelson_core::mod_fn(move |t: &mut UserTemplate| t.posts.push(tpl))
    }
    impl UserTemplate {
        /// The no-database strategy: the setter `create` would insert. No executor in the signature — that absence is the guarantee.
        pub fn build(
            &self,
            f: &mut keelson_factory::Faker,
        ) -> super::super::users::Setter {
            super::super::users::Setter {
                id: self.id.resolve(f, |_| keelson_models::Set::Value(SEQ.next_i64())),
                name: self
                    .name
                    .resolve(
                        f,
                        |f| keelson_models::Set::Value(format!("user-{}", f.alnum(8))),
                    ),
                email: self
                    .email
                    .resolve(
                        f,
                        |f| keelson_models::Set::Value(format!("user-{}", f.alnum(8))),
                    ),
                age: self
                    .age
                    .resolve(f, |f| keelson_models::Set::Value(f.i64_in(1, 1000))),
                is_active: self.is_active.resolve(f, |_| keelson_models::Set::Unset),
                created_at: self.created_at.resolve(f, |_| keelson_models::Set::Unset),
            }
        }
        /// Create the parent chain (unless overridden), the row itself through the model's own insert path — so hooks fire — and then the queued children. Boxed rather than an `async fn` because factory graphs recurse.
        pub fn create_with<'a>(
            &'a self,
            db: &'a dyn keelson_exec::Executor,
            f: &'a mut keelson_factory::Faker,
        ) -> keelson_exec::ExecFuture<
            'a,
            Result<super::super::users::User, keelson_exec::ExecError>,
        > {
            Box::pin(async move {
                let s = self.build(f);
                let row = super::super::users::table().insert(s).one(db).await?;
                for c in &self.comments {
                    let mut child = c.clone();
                    child.user = keelson_factory::OptionalParent::Existing(row.id);
                    child.create_with(db, &mut *f).await?;
                }
                for c in &self.posts {
                    let mut child = c.clone();
                    child.user = keelson_factory::Parent::Existing(row.id);
                    child.create_with(db, &mut *f).await?;
                }
                Ok(row)
            })
        }
        /// Create one row (and whatever parents and children the template implies) with a fresh entropy-seeded faker.
        pub async fn create(
            &self,
            db: &dyn keelson_exec::Executor,
        ) -> Result<super::super::users::User, keelson_exec::ExecError> {
            let mut f = keelson_factory::Faker::from_entropy();
            self.create_with(db, &mut f).await
        }
        /// Create `n` rows; sequences keep the unique columns apart.
        pub async fn create_many(
            &self,
            db: &dyn keelson_exec::Executor,
            n: usize,
        ) -> Result<Vec<super::super::users::User>, keelson_exec::ExecError> {
            let mut f = keelson_factory::Faker::from_entropy();
            let mut out = Vec::with_capacity(n);
            for _ in 0..n {
                out.push(self.create_with(db, &mut f).await?);
            }
            Ok(out)
        }
    }
}
