// @generated by keelson-gen. DO NOT EDIT.
// Regenerate from the schema instead; hand-written code (hooks included)
// belongs outside this directory.

//! The generated models, one module per table.

pub mod audit_logs;
pub mod comments;
pub mod post_authors;
pub mod post_tags;
pub mod posts;
pub mod tags;
pub mod users;

/// The generated test-data factories, one module per writable table.
pub mod factories;
