// @generated by keelson-gen. DO NOT EDIT.
// Regenerate from the schema instead; hand-written code (hooks included)
// belongs outside this directory.

/// The model marker `post_tags::table()` hangs off.
#[derive(Debug, Clone, Copy)]
pub struct PostTags;
/// One row of `post_tags`.
#[derive(Debug, Clone, PartialEq)]
pub struct PostTag {
    pub post_id: i64,
    pub tag_id: i64,
    /// Relations, filled by `preload`/`then_load` mods; empty otherwise.
    pub rel: Rel,
}
/// `post_tags`' relations.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Rel {
    /// Belongs-to `posts`, via `post_tags.post_id`.
    pub post: Option<Box<super::posts::Post>>,
    /// Belongs-to `tags`, via `post_tags.tag_id`.
    pub tag: Option<Box<super::tags::Tag>>,
}
impl keelson_exec::FromRow for PostTag {
    fn from_row(row: &mut keelson_exec::Row) -> Result<Self, keelson_exec::ExecError> {
        Ok(PostTag {
            post_id: row.take("post_id")?,
            tag_id: row.take("tag_id")?,
            rel: Rel::default(),
        })
    }
}
/// The three-state setter: unset fields stay out of the statement.
#[derive(Debug, Clone, Default)]
pub struct Setter {
    pub post_id: keelson_models::Set<i64>,
    pub tag_id: keelson_models::Set<i64>,
}
/// The entry point: `post_tags::table().query(…)` / `.insert(…)` / ….
pub fn table() -> keelson_models::ModelTable<PostTags> {
    keelson_models::ModelTable::new()
}
pub fn post_id() -> keelson_models::Column<i64> {
    keelson_models::Column::new("post_tags", "post_id")
}
pub fn tag_id() -> keelson_models::Column<i64> {
    keelson_models::Column::new("post_tags", "tag_id")
}
#[allow(clippy::type_complexity)]
fn all_columns() -> (keelson_models::Column<i64>, keelson_models::Column<i64>) {
    (post_id(), tag_id())
}
impl keelson_models::View for PostTags {
    type Row = PostTag;
    type Select = keelson_sqlite::SelectQuery;
    fn base_select() -> Self::Select {
        keelson_sqlite::select((
            keelson_sqlite::select::columns(all_columns()),
            keelson_sqlite::select::from(keelson_sqlite::quote("post_tags")),
        ))
    }
}
impl keelson_models::Table for PostTags {
    type Pk = (i64, i64);
    type Setter = Setter;
    type Insert = keelson_sqlite::InsertQuery;
    type Update = keelson_sqlite::UpdateQuery;
    type Delete = keelson_sqlite::DeleteQuery;
    fn insert_query(s: Setter) -> Self::Insert {
        let mut cols: Vec<&'static str> = Vec::new();
        let mut vals: Vec<keelson_core::expr::Expr> = Vec::new();
        s.post_id.push_into("post_id", &mut cols, &mut vals);
        s.tag_id.push_into("tag_id", &mut cols, &mut vals);
        let mut q = keelson_sqlite::insert((
            keelson_sqlite::insert::into(keelson_sqlite::quote("post_tags"))
                .columns(cols),
            keelson_sqlite::insert::returning(all_columns()),
        ));
        if !vals.is_empty() {
            q.apply(keelson_sqlite::insert::values(vals));
        }
        q
    }
    fn update_query() -> Self::Update {
        keelson_sqlite::update(
            keelson_sqlite::update::table(keelson_sqlite::quote("post_tags")),
        )
    }
    fn apply_setter(s: Setter, q: &mut Self::Update) {
        if let Some(v) = s.post_id.into_expr() {
            q.apply(keelson_sqlite::update::set_col("post_id").to(v));
        }
        if let Some(v) = s.tag_id.into_expr() {
            q.apply(keelson_sqlite::update::set_col("tag_id").to(v));
        }
    }
    fn delete_query() -> Self::Delete {
        keelson_sqlite::delete(
            keelson_sqlite::delete::from(keelson_sqlite::quote("post_tags")),
        )
    }
    fn pk(row: &PostTag) -> Self::Pk {
        (row.post_id, row.tag_id)
    }
}
/// Preload mods: the relation joins into the *same* query — no second statement, and deliberately no `.then(…)`. A level below a join has no distinct child set to key on, so a nested path is spelled with `then_load` (see `keelson_models::ThenLoad`).
pub mod preload {
    /// Same-query `LEFT JOIN` preload of the to-one `post`.
    pub fn post() -> impl keelson_core::Mod<
        keelson_models::ModelSelect<super::PostTags>,
    > {
        keelson_core::mod_fn(|q: &mut keelson_models::ModelSelect<super::PostTags>| {
            use keelson_sqlite::Chain as _;
            use keelson_sqlite::Mod as _;
            (
                keelson_sqlite::select::left_join(keelson_sqlite::quote("posts"))
                    .on(
                        keelson_sqlite::quote(("posts", "id"))
                            .eq(keelson_sqlite::quote(("post_tags", "post_id"))),
                    ),
                keelson_sqlite::select::preload_columns((
                    keelson_sqlite::quote(("posts", "id")).as_("post.id"),
                    keelson_sqlite::quote(("posts", "user_id")).as_("post.user_id"),
                    keelson_sqlite::quote(("posts", "title")).as_("post.title"),
                    keelson_sqlite::quote(("posts", "status")).as_("post.status"),
                    keelson_sqlite::quote(("posts", "views")).as_("post.views"),
                    keelson_sqlite::quote(("posts", "published_at"))
                        .as_("post.published_at"),
                )),
            )
                .apply(q);
            q.add_mapper_mod(
                keelson_models::mapper_mod(|row, parent: &mut super::PostTag| {
                    parent.rel.post = post_from_preload(row)?.map(Box::new);
                    Ok(())
                }),
            );
        })
    }
    /// Decode the prefixed columns; the joined key column decides a `LEFT JOIN` miss.
    pub fn post_from_preload(
        row: &mut keelson_exec::Row,
    ) -> Result<Option<super::super::posts::Post>, keelson_exec::ExecError> {
        if matches!(row.value("post.id"), None | Some(keelson_sqlite::Value::Null)) {
            return Ok(None);
        }
        Ok(
            Some(super::super::posts::Post {
                id: row.take("post.id")?,
                user_id: row.take("post.user_id")?,
                title: row.take("post.title")?,
                status: row.take("post.status")?,
                views: row.take("post.views")?,
                published_at: row.take("post.published_at")?,
                rel: super::super::posts::Rel::default(),
            }),
        )
    }
    /// Same-query `LEFT JOIN` preload of the to-one `tag`.
    pub fn tag() -> impl keelson_core::Mod<
        keelson_models::ModelSelect<super::PostTags>,
    > {
        keelson_core::mod_fn(|q: &mut keelson_models::ModelSelect<super::PostTags>| {
            use keelson_sqlite::Chain as _;
            use keelson_sqlite::Mod as _;
            (
                keelson_sqlite::select::left_join(keelson_sqlite::quote("tags"))
                    .on(
                        keelson_sqlite::quote(("tags", "id"))
                            .eq(keelson_sqlite::quote(("post_tags", "tag_id"))),
                    ),
                keelson_sqlite::select::preload_columns((
                    keelson_sqlite::quote(("tags", "id")).as_("tag.id"),
                    keelson_sqlite::quote(("tags", "name")).as_("tag.name"),
                )),
            )
                .apply(q);
            q.add_mapper_mod(
                keelson_models::mapper_mod(|row, parent: &mut super::PostTag| {
                    parent.rel.tag = tag_from_preload(row)?.map(Box::new);
                    Ok(())
                }),
            );
        })
    }
    /// Decode the prefixed columns; the joined key column decides a `LEFT JOIN` miss.
    pub fn tag_from_preload(
        row: &mut keelson_exec::Row,
    ) -> Result<Option<super::super::tags::Tag>, keelson_exec::ExecError> {
        if matches!(row.value("tag.id"), None | Some(keelson_sqlite::Value::Null)) {
            return Ok(None);
        }
        Ok(
            Some(super::super::tags::Tag {
                id: row.take("tag.id")?,
                name: row.take("tag.name")?,
                rel: super::super::tags::Rel::default(),
            }),
        )
    }
}
/// Then-load mods: one keyed, batched query per level of a load path — `then_load::a().then(b::then_load::c())` is two levels, two queries, checked by the compiler.
pub mod then_load {
    /// Load each row's `post` (to-one), one keyed query per batch of keys — `.then(…)` hangs the next level of the path off this one.
    pub fn post() -> keelson_models::ThenLoad<
        super::PostTags,
        super::super::posts::Posts,
        i64,
    > {
        keelson_models::ThenLoad::new(
            |rows: &[super::PostTag]| rows.iter().map(|r| r.post_id).collect(),
            |keys, q| keelson_core::Mod::apply(super::super::posts::id().in_(keys), q),
            |rows: &mut [super::PostTag], related| {
                keelson_models::attach_to_one(
                    rows,
                    related,
                    |r| r.post_id,
                    |c| c.id,
                    |r, c| {
                        r.rel.post = c.map(Box::new);
                    },
                );
            },
        )
    }
    /// Load each row's `tag` (to-one), one keyed query per batch of keys — `.then(…)` hangs the next level of the path off this one.
    pub fn tag() -> keelson_models::ThenLoad<
        super::PostTags,
        super::super::tags::Tags,
        i64,
    > {
        keelson_models::ThenLoad::new(
            |rows: &[super::PostTag]| rows.iter().map(|r| r.tag_id).collect(),
            |keys, q| keelson_core::Mod::apply(super::super::tags::id().in_(keys), q),
            |rows: &mut [super::PostTag], related| {
                keelson_models::attach_to_one(
                    rows,
                    related,
                    |r| r.tag_id,
                    |c| c.id,
                    |r, c| {
                        r.rel.tag = c.map(Box::new);
                    },
                );
            },
        )
    }
}
